# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

# define hostname
NAME = "iobroker-base"
# define basebox
DEFAULT_BOX_IMAGE = "bento/debian-10"
PRIVNET_1_IPADDR = "192.168.56.60"
# In virtualbox usually one private network is predefined with 192.168.56.0/24

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.define NAME
  config.vm.box = DEFAULT_BOX_IMAGE
  config.vm.synced_folder "../../_common", "/vagrant_common"
  config.vm.synced_folder "../../data", "/data"
  config.vm.network "private_network", ip: PRIVNET_1_IPADDR
  config.vm.hostname = NAME
  # end
  config.vm.provider "virtualbox" do |v|
    v.name = "#{NAME}-#{PRIVNET_1_IPADDR}"
    v.memory = "2048"
    v.cpus = "2"
  end
  #config.vm.provision "ansible_local" do |ansible|
  #  ansible.playbook = "/vagrant_common/ansible/playbooks/p-install-docker-ce.yml"
  #  #ansible.playbook = "/vagrant_common/ansible/playbooks/p-update-os.yml"
  #end
end